version: 2
jobs:
  build:
    environment:
      LC_ALL: c.UTF-8
      LANG: c.UTF-8
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get -y install make gawk rlwrap emacs
      - run:
          name: Sanity Check
          command: make check
