version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get -y install make gawk rlwrap emacs
      - run:
          name: Sanity Check
          command: |
            locale-gen en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            make check
