version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get -y install locales make gawk rlwrap emacs
      - run:
          name: Sanity Check
          command: |
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            make check
