version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get install build-essential
      - run:
          name: Sanity Check
          command: make check
